[package]
name = "flappy-bird"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = "0.2.2"
itertools = "0.10.0"
oorandom = "11.1.3"
bevy = { version = "0.6" }

[profile.dev.package.bevy]
opt-level = 1

[profile.release]
opt-level = 's'
lto = true