[package]
name = "game"
version = "0.1.0"
authors = ["Knarkzel <knarkzel@gmail.com>"]
edition = "2018"

[dependencies]
bevy = { path = "bevy", features = ["dynamic"] }
neuralnetwork = { path = "neuralnetwork" }
knarkzel = "0.6"

[profile.dev.package.bevy]
opt-level = 1
